version: '3.0'
services:

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server
    container_name: server
    privileged: true
    hostname: server.nfs.local
    networks:
      - nfs
    environment:
      NFS_SERVER_DIRS: '/volume/dir1:/volume/dir2'
    volumes:
      - ./server/server_volume:/volume

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client
    container_name: client
    privileged: true
    hostname: client.nfs.local
    networks:
      - nfs
    environment:
      NFS_SERVER: server
      NFS_SERVER_DIRS: '/volume/dir1:/volume/dir2'
      NFS_CLIENT_DIRS: '/volume/dir1:/volume/dir2'
    volumes:
      - ./client/client_volume:/volume

networks:
  nfs:
